// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg2hLlWTtBdC5jJDoEllltO5x8Nh_w6WQ',
    appId: '1:904728524309:web:b892f2f0c9ca1a6e91401c',
    messagingSenderId: '904728524309',
    projectId: 'minhas-tarefas-dd0c5',
    authDomain: 'minhas-tarefas-dd0c5.firebaseapp.com',
    storageBucket: 'minhas-tarefas-dd0c5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW12rKXILeKfviNlphsi7UqsyC3yVv5KA',
    appId: '1:904728524309:android:53036d5a9741435891401c',
    messagingSenderId: '904728524309',
    projectId: 'minhas-tarefas-dd0c5',
    storageBucket: 'minhas-tarefas-dd0c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT5sy9b5WZw6btE1adhnppnZScEySqewk',
    appId: '1:904728524309:ios:902bf630fef616ee91401c',
    messagingSenderId: '904728524309',
    projectId: 'minhas-tarefas-dd0c5',
    storageBucket: 'minhas-tarefas-dd0c5.appspot.com',
    iosBundleId: 'com.example.layout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT5sy9b5WZw6btE1adhnppnZScEySqewk',
    appId: '1:904728524309:ios:49ce1f88aeb1c92691401c',
    messagingSenderId: '904728524309',
    projectId: 'minhas-tarefas-dd0c5',
    storageBucket: 'minhas-tarefas-dd0c5.appspot.com',
    iosBundleId: 'com.example.layout.RunnerTests',
  );
}
